config/routes.rb
Rails.application.routes.draw do
  mount ChinaCity::Engine => '/china_city'
  resources :orders
    get 'orders/submitorder/:id',  to:  'orders#submitorder'
  resources :cars   do
    collection  do
      get 'reduce'
      get 'add'
      get 'count'
      get 'count_num'
    end
  end

  resources :products
  get 'welcome/index'

  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
  resources :types
     get 'deletecheck', to: 'types#deletecheck'
   resources  :books   do
     collection  do
      get  'batch_add'   
      get  'checkname'
     end
     end
    get  '/checktypeid/:type_id',  to:  'books#checktypeid'
   resources  :infos
   resources  :languages
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  before_filter :authenticate_user!
  
   def  deletecheck 
     if   params[:type_ids].nil?
     else
       params[:type_ids].each  do  |ids|
       @type = Type.where( " id  = #{ids} " ).update_all( "con = 0 ")
       end
     end
     redirect_to  :back
   end

  def  new
      @type  =  Type.new 
    end

    def  index
      @types = Type.paginate( :page  =>  params[:page]||1,
                                                        :per_page  =>  5).order("created_at desc").where("con = 1")
      
      respond_to do |format|  
        format.html # index.html.erb  
        format.csv { send_data @types.to_csv }  
        format.xls  
          #    format.xls { send_data @week_plans.to_csv(col_sep: "\t") }  
        format.json { render :json => @types }  
          end
    end
    
     def  create
       @type = Type.new(type_params)
       
       if  @type.save
        redirect_to types_path
       else
          render 'new'
       end 
     end

     def  show
      puts  params[:id]
      params[:id] = params[:id].to_i
        @books  =  Book.paginate( :page  =>  params[:page]||1,
                                                              :per_page  =>  5).order("created_at desc").where("type_id = #{params[:id]}  and  con = 1")
     end

      def  edit
        @type  =  Type.find(params[:id])
      end

      def  update
        @type = Type.find(params[:id])
       
        if @type.update(type_params)
          redirect_to types_path
        else
          render 'edit'
        end
      end

    def  destroy
      if  params[:id]  ==  "a"
        @id = Type.find_by_sql("select c.id from (select types.id ,COUNT(case when books.con = 1 then 1 end) as count
                                                       from types left JOIN books on types.id = books.type_id GROUP BY types.id)c where c.count = 0").collect{|t|  t.id}
        @id = "#{@id}"
        @id = @id[1..-2]
        @type = Type.where( " id in (#{@id})" ).update_all( "con = 0 ")
        redirect_to "/types"
      elsif  params[:id]  == "b"
        @type = Type.where( " con = 0" ).update_all( "con = 1 ")
        redirect_to "/types"
      else
        @type = Type.where( " id  = #{params[:id]} " ).update_all( "con = 0 ")
        redirect_to :back
      end
    end
    
  private
    def  type_params
    	params.require(:type).permit(:b_type)
    end 
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_f.html.erb
<div class="form-group">
  <%= f.label :b_type, :class => 'control-label' %>
  <%= f.text_field :b_type, :class => 'form-control', required: true %>
</div>

app/views/types/_form.html.erb
<%=  form_for  @type,  :remote  => true   do  |f|  %>
  <table  id="nt_tab">
    <tr>
      <td  id="nt_tdl">
        <%=  f.label  :类型  %>
      </td>
      <td>
        <%=  f.text_field  :b_type,  :placeholder  =>  '2-15字符'  %>
      </td>
      <td  id="nt_tdr">
        <span id="error"> 
          <%  if  !@type.errors[:b_type].blank?  %>
          <%=  @type.errors[:b_type][0]  %>
          <%  end  %>
        </span>
      </td>
    </tr>
    <tr>
      <td  colspan="2"><%=  f.submit '保存',  :data => { :"disable-with" => "请稍等..." }  %></td>
      <td></td>
    </tr>
  </table>
<%  end  %>

app/views/types/destroy.js.erb
$('#type_<%= type.id  %>').fadeOut();

app/views/types/edit.html.erb
<style type="text/css">
  #e_t_d{
    height: 297px;
    width: 1280px;
  }
  #error_explanation{
      height: 100px;
      width:400px;
      font-size: 16px;
      line-height: 2px;
      text-align: left;
  }
  #n_t_d{
    height: 297px;
    width: 1280px;
  }
  #error{
   height: 30px;
   color: red;
   font-size: 10px;
   line-height: 10px;
  }

  #nt_tab{
     width: 400px;
     height: 50px;
     text-align: center;
     border: 1px;
     font-size: 18px;
     font-weight: normal;
  }
  #nt_tdl{
    width: 50px;
    text-align: center;
  }
  #nt_tdr{
    width: 150px;
    text-align: center;
</style>
<center>
<div  id="e_t_d">
<h3>更新</h3>
<%= render 'form' %>
</div>
</center>

app/views/types/index.html.erb
<script type="text/javascript">
  function toggle_checkall(field_name, state) {
    var checkboxes = document.getElementsByTagName("input");
    var count = checkboxes.length;
    for (var i = 0; i < count; i++) {
      if (checkboxes[i].type == "checkbox"
          && checkboxes[i].name == field_name + "_ids[]") {
        checkboxes[i].checked = state;
      }
    }
  }
</script>
<center>
<div>
<%=  form_tag  books_path,   method:  :get,  :onsubmit  => "return a()"  do  %>
  书名:<%=   radio_button_tag  "se_t",  "name", "checked"  %>
  作者:<%=   radio_button_tag  "se_t",  "author" %>
  出版时间:<%=   radio_button_tag  "se_t",  "p_time" %>
  类别:<%=   radio_button_tag  "se_t",  "b_type" %>
  全文:<%=   radio_button_tag  "se_t",  "all" %>
  <%=  text_field_tag  :search %>
  <%=  submit_tag '搜索'  %>
<%  end  %>
<%=  link_to  "delete  empty",  "types/a" , remote: true,  method:  :delete %>
<%=  link_to  "recovery",  "types/b" , remote: true,  method:  :delete %>
<%=  form_tag  books_path,  method:  :get  do  %>
  <input type="hidden" name="user_id" value="<%=  current_user.id %>">
  <input type="hidden" name="a" value= 1 >
  <%=  submit_tag  '查询已借出'  %>
<%  end  %>
<div  id="i_tab_d">
<%=  form_tag("/deletecheck",  method:  "get", 
                                                            data: { confirm: '确定删除？'})   do %>
<table  id = "i_tab">
<caption>图书列表</caption>
  <tr class = "tr1"  >
    <th>图书类别</th>
    <th colspan="3">管理</th>
    <th>种数</th>
    <th>
      <input type="checkbox"  id="checked" 
                    onclick="toggle_checkall('type', this.checked);" /><%= submit_tag "删除选中" %>
      </th>
  </tr>
  <%  if  @types.size == 0  %>
  <tr>
    <td  colspan="6">记录为空</td>
  </tr>
  <%  else  %>

  <% @types.each do |type| %>
    <tr  id="type_<%= type.id %>">
      <td><%=  type.b_type %></td>
      <td><%= link_to '查看', type_path(type) %></td>
      <td><%= link_to '更新', edit_type_path(type)  %></td>
      <td><%= link_to '删除', type_path(type),  method: :delete, 
                                                                                     remote: true,
                                                                                     data: { confirm: '确定删除？'}%></td>
        <td><%= Book.con(type.id)  %></td>
        <td><%=  check_box_tag "type_ids[]", type.id %> </td>
      </tr>
  <% end %>
  <%  end  %>
</table>
<%  end  %>
</div>
<div   id="page">
  <%=  will_paginate  @books   %>
</div>
  <%= link_to "CSV", types_path(format: "csv") %>  
  <%= link_to "EXCEL", types_path(format: "xls") %>  

<div class='html-tag city-group'>
<%#=  form_tag("/deletecheck",  method:  "get")   do %>
  <select class='city-select city-province'  name="province">
    <option> --省份--</option>
    <%= options_for_select(ChinaCity.list)  %>
  </select>
  <select class='city-select city-city'  name="city">
    <option>--城市--</option>
  </select>
  <select class='city-select city-district'  name="district">
    <option>--地区--</option>
  </select>
<%#= submit_tag "submit" %>
<%#  end  %>
</div>
<!-- <%#=  select_month(Date.today)  %><%#=  select_day(12)  %>
time<%#=  select_time(Time.now)  %>hour<%#=  select_hour(5)  %>
<%#=  select_minute(15)  %><%#=  select_second(Time.now)  %>
<%#=  select_year(2011,  :field_name  =>  'birth',  :start_year  =>  1900)  %> -->
</center>

app/views/types/index.xls.erb
<table  border="1">
<caption>图书列表</caption>
  <tr class = "tr1">
    <th>图书类别</th>
    <th>种数</th>
  </tr>
  <%  if  @types.size == 0  %>
  <tr>
    <td  colspan="6">记录为空</td>
  </tr>
  <%  else  %>
  <% @types.each do |type| %>
    <tr  id="type_<%= type.id %>">
      <td><%=  type.b_type %></td>
      <td><%= Book.con(type.id)  %></td>
    </tr>
  <% end %>
  <%  end  %>
</table>

app/views/types/new.html.erb
<center>
<div  id="n_t_d">
<%= render 'form' %>
</div>
</center>

app/views/types/show.html.erb
<center>
<div  id="tab">
<table id = "n_tab_t">
<caption>图书列表</caption>
  <tr class = "tr1">
    <th>图书类别</th>
    <th>图书名称</th>
    <th>可借数量</th>
    <th>借出数量</th>
    <th colspan="4">管理</th>
    <th>修改</th>
  </tr>
  <%  if  @books.size == 0  %>
  <tr>
    <td  colspan="7">记录为空</td>
  </tr>
  <%  else  %>
  <% @books.each do |book| %>
  <tr>
    <td><%=  Type.find_btype(book.type_id)%></td>
    <td><%=  book.name %></td>
    <td><%=  book.num %></td>
    <td>
      <%  if Book.find_ubn(book.id,current_user.id).nil? %>
        0
      <%  else  %>
        <%=  Book.find_ubn(book.id,current_user.id)  %>
      <%  end  %>
    </td>
    <td style="width:85px;">
    <%  if Book.find_ubn(book.id,current_user.id)  == 0   || Book.find_ubn_e(book.id,current_user.id)  ==  0  %>
      <span  style="font-size: 12px;">无借出</span>
    <%  else  %>
    <%=  form_for :book,  url: book_path(book.id) ,  
                                               remote:  true,
                                               method: :patch  do  |f| %>
   <input type="hidden" name="num" value=1/>
   <%=  f.hidden_field  :type_id,  :value  =>  book.type_id  %>
   <%=  f.hidden_field  :user_id,  :value  =>  current_user.id  %>
   <%=  f.submit  '还入'  %>
   <%  end  %>
   <%  end  %>
   </td>
    <td>
     <%  if  book.num >0  %>
     <%=  form_for :book,   url: book_path(book.id) ,
                                                 remote:  true,
                                                 method: :patch    do  |f| %>
     <input type="hidden" name="num" value=0/>
     <%=  f.hidden_field  :type_id,  :value  =>  book.type_id  %>
     <%=  f.hidden_field  :user_id,  :value  =>  current_user.id  %>
     <%=  f.submit  '借出'  %>
     <%  end  %>
     <%  else %>
      不可借
     <% end %>
   </td>
   <td>
   <%=  form_for :book,   url: book_path(book.id) ,  
                                               method: :delete, 
                                               remote:  true,  
                                               data: { confirm: '确定删除？'}  do  |f| %>
   <%=  f.hidden_field  :id,  :value  =>  book.id  %>
   <%=  f.hidden_field  :type_id,  :value  =>  book.type_id  %>
   <%=  f.submit  '删除'  %>
   <%  end  %>                                                                                       
   </td>
   <td><%= link_to '查看', book_path(book) %></td>
   <td>
     <%=  link_to  '修改',edit_book_path(book)  %>
   </td>
       <%#= check_box_tag 'che', book.id %>
 </tr>
<% end %>
<%  end  %>
</table>
</div>
<div   id="page">
  <%=  will_paginate  @books   %>
</div>
</center>