config/routes.rb
Rails.application.routes.draw do
  mount ChinaCity::Engine => '/china_city'
  resources :orders
    get 'orders/submitorder/:id',  to:  'orders#submitorder'
  resources :cars   do
    collection  do
      get 'reduce'
      get 'add'
      get 'count'
      get 'count_num'
    end
  end

  resources :products
  get 'welcome/index'

  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
  resources :types
     get 'deletecheck', to: 'types#deletecheck'
   resources  :books   do
     collection  do
      get  'batch_add'   
      get  'checkname'
     end
     end
    get  '/checktypeid/:type_id',  to:  'books#checktypeid'
   resources  :infos
   resources  :languages
end

app/models/order.rb
class Order < ApplicationRecord

end

app/models/product.rb
class Product < ApplicationRecord
  has_and_belongs_to_many  :car
  has_and_belongs_to_many :order

  private

  def  self.find_p_name(id)
    Product.find_by_sql("select p_name from products where id = #{id}").collect{|t| t.p_name}[0]
  end

  def  self.find_p_price(id)
    Product.find_by_sql("select p_price from products where id = #{id}").collect{|t| t.p_price}[0]
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create

    puts params[:car_ids]
    puts params[:c_num]
    @order = Order.new(order_params)
    puts @order.save
      if @order.save
        puts order_params[:car_ids]
        Car.setcar_con(order_params[:car_ids])
        redirect_to  @order  
      else
        redirect_to  :back
      end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def  submitorder
    puts params[:id]
    @order  = Order.where("id = #{params[:id]}").update_all("pay_con = 3")
    redirect_to  'submitorder'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:car_ids,  :b_num,  :cost)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_info %>
    <%= f.text_field :order_info %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Order info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_info %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order info:</strong><br>
  订单提交成功，请选择支付<br/>
  订单编号 : <%=  @order.id  %><br/>
  订单明细 : <%=  Car.find_pro_id(@order.car_ids) %><br/>
  商品总额 : <%=  @order.cost  %><br/>
  商品数量 : <%=  @order.b_num  %><br/>
  支付状态 : <%=   @order.pay_con == 3 ? '已支付':'未支付'  %>
</p>
<%  if  @order.pay_con == 2  %>
  <%=  link_to  '点击支付', {:controller => "orders",   :action => "submitorder",  :id  =>  @order.id},   :remote => true  %>
<%  end  %>
<%=  link_to  '返回购物车', cars_path  %><br/>

app/views/orders/submitorder.html.erb
支付成功
<%=  link_to  '返回购物车', cars_path  %><br/>
<%=  link_to  '返回商品', products_path  %>