config/routes.rb
Rails.application.routes.draw do
  mount ChinaCity::Engine => '/china_city'
  resources :orders
    get 'orders/submitorder/:id',  to:  'orders#submitorder'
  resources :cars   do
    collection  do
      get 'reduce'
      get 'add'
      get 'count'
      get 'count_num'
    end
  end

  resources :products
  get 'welcome/index'

  devise_for :users, controllers: { sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
  resources :types
     get 'deletecheck', to: 'types#deletecheck'
   resources  :books   do
     collection  do
      get  'batch_add'   
      get  'checkname'
     end
     end
    get  '/checktypeid/:type_id',  to:  'books#checktypeid'
   resources  :infos
   resources  :languages
end

app/models/book.rb
class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_one :info
  belongs_to :type
  
  validates  :num,  :numericality => {:greater_than_or_equal_to  =>  0,  :message => '需大于等于0'},  :presence => {message: "blank" }
  validates  :name,  length:{ in: 1..50,  message: '1-50字符'},  uniqueness:{message:'已经存在此书籍'},  :presence => {message: "blank" }
  validates  :picture,  :format  =>  {:with  =>  /\.(gif|jpg|jpeg|png|GIF|JPG|PNG)$/,  :multiline => true,  :message  =>  'must be a url for git,jpg or png  image'  }
  private
  def  self.con(id)
    Book.where("type_id = #{id}").count(1)
  end
  
  #获取借出本书
  def  self.find_ubn(id1,id2)
   Book.find_by_sql("select b.ubn from  borrow b  where b.book_id = #{id1} and b.user_id = #{id2}").collect{|t| t.ubn}[0]
  end

  def  self.find_ubn_e(id1,id2)
   Book.find_by_sql("select b.ubn from  borrow b  where b.book_id = #{id1} and b.user_id = #{id2}").size
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :authenticate_user!
  
  def  new
    @book  =  Book.new 
  end

  def  index
    if  !params[:user_id].nil?
      @borrow  =  Book.find_by_sql("select * from borrow where ubn>0 and user_id = #{params[:user_id]}").collect{|t| t.book_id}
      @borrow  =  "#{@borrow}"
      @borrow  =  @borrow[1..-2]

      @book  =   Book.paginate( :page  =>  params[:page]||1,
                                                           :per_page  =>  5).order("created_at").where("con = 1 and id in (#{@borrow})")
      @books = nil
    else

      @type =  Type.where("b_type like '%#{params[:search]}%'").collect{|t| t.id}
      @type = "#{@type}"
      @type = @type[1..-2]
      if @type.size  ==  0
        @type  = 0
      end

      @info  =  Info.where("author  like '%#{params[:search]}%'").collect{|t|  t.book_id}
      @info  =  "#{@info}"
      @info  =  @info[1..-2]
      if @info.size  ==  0
        @info  = 0
      end

      @infos  =  Info.where("p_time  like '%#{params[:search]}%'").collect{|t|  t.book_id}
      @infos  =  "#{@infos}"
      @infos  =  @infos[1..-2]
      if @infos.size  ==  0
        @infos  = 0
      end

  	if  params[:search] .nil?
  	   @books = Book.paginate( :page  =>  params[:page]||1,
  	                                                       :per_page  =>  5).order("type_id").where("con = 1")
  	  elsif   params[:se_t]  ==  'name'
  	    @books = Book.paginate( :page  =>  params[:page]||1,
  	                                                        :per_page  =>  5).order("created_at desc").where("con = 1  and  name  like  '%#{params[:search]}%'")
  	  elsif   params[:se_t]  ==  'b_type'  
  	    @books = Book.paginate( :page  =>  params[:page]||1,
                                                                :per_page  =>  5).order("created_at desc").where("con = 1  and  type_id  in (#{@type})")
        elsif  params[:se_t]  ==  'all'   

          @books = Book.paginate( :page  =>  params[:page]||1,
  	                                                      :per_page  =>  5).order("created_at desc").where("con = 1  and (type_id  in (#{@type})  
                                                                                                                                                               or   id in(#{@info}) or  id in(#{@infos}) 
                                                                                                                                                               or   name  like  '%#{params[:search]}%')")
        elsif  params[:se_t]  ==  'author'
          @books  =   Book.paginate( :page  =>  params[:page]||1,
                                                                 :per_page  =>  5).order("created_at desc").where("con = 1  and  id in(#{@info}) ")
        else
          @books  =   Book.paginate( :page  =>  params[:page]||1,
                                                                 :per_page  =>  5).order("created_at desc").where("con = 1  and  id in(#{@infos}) ")  
  	  end
    end
  end	

  def  create
    @b = book_params[:name]
    @book = Book.new(book_params)
    if @book.valid?  &&  @book.save
      redirect_to "/types/#{book_params[:type_id]}"
   else
       render 'new'
    end
  end

  def  update 

    sql = ActiveRecord::Base.connection() 
    print b_params[:user_id],"user_id  value"
    puts  params[:num]

    if  params[:num]  ==  "1"
      @book = Book.where( " id = #{params[:id]} " ).update_all( "num = num + 1, bn = bn - 1")
      sql.update"update  borrow  set ubn = ubn - 1  where  book_id = #{params[:id]} and user_id = #{b_params[:user_id]}"
      
      redirect_to "/types/#{book_params[:type_id]}"

    elsif  params[:num]  ==  "0" 

       @book = Book.where( " id  = #{params[:id]} " ).update_all( "num = num - 1, bn = bn + 1") 
        if  find_c_exit(params[:id],b_params[:user_id]) > 0
           sql.update"update  borrow  set ubn = ubn + 1  where  book_id = #{params[:id]} and user_id = #{b_params[:user_id]}"
         else
          sql.insert"insert into borrow(ubn,book_id,user_id)  values(1,#{params[:id]},  #{b_params[:user_id]})"
        end
        redirect_to "/types/#{book_params[:type_id]}"
    elsif  params[:num]  ==  "2"

       @book = Book.where( " id = #{params[:id]} " ).update_all( "num = num + #{b_params[:bn]}, bn = bn - #{b_params[:bn]}")
       sql.update"update  borrow  set ubn = ubn - #{b_params[:bn]}  where   book_id = #{params[:id]} and user_id = #{b_params[:user_id]}"
       redirect_to "/books/#{params[:id]}"

    elsif  params[:num]  ==  "3"
       @book = Book.where( " id = #{params[:id]} " ).update_all( "num = num - #{b_params[:bn]}, bn = bn + #{b_params[:bn]}" )
        if  find_c_exit(params[:id],b_params[:user_id]) > 0
           sql.update"update  borrow  set ubn = ubn +  #{b_params[:bn]}  where
                                      book_id = #{params[:id]} and user_id = #{b_params[:user_id]}"
         else
          sql.insert"insert into borrow(ubn,book_id,user_id)  
                                values(#{b_params[:bn]},#{params[:id]},  #{b_params[:user_id]})"
        end
       redirect_to "/books/#{params[:id]}"
    else

       @book = Book.find(params[:id])
       if @book.update(book_params)
         redirect_to "/books/#{params[:id]}"
       else
         render 'edit'
       end
    end
  end

  def  edit
    @book  =  Book.find(params[:id])
  end

  def  destroy
    @book =  Book.where( " id  = #{params[:id]} " ).update_all( "con = 0 ")
    redirect_to :back
  end

  def  show
    @books  =  Book.find(params[:id])
    @info  =  Info.where("book_id = #{params[:id]}")
  end

  def  checktypeid
    type_id  =  params[:type_id]
    render :text => infoadd(type_id)
  end

  def  infoadd(type_id)
    @info =  Info.all.collect{|t| t.book_id}
    @info = "#{@info}"
    puts  @info
    @info = @info[1..-2]

    options = ""
    books = Book.order("created_at desc").where("type_id =  #{type_id} and id not in (#{@info}) ")
    books.each do |book|
      options << "<option value='#{book.id}'>#{book.name}</option>"
    end
    return options
  end

  def  checkname
    puts params[:name]
    book = Book.find_by_name(params[:name])
    if  book.nil?
      render  :text  =>  true
    else 
      render  :text  =>  false
    end
  end

  def  batch_add
    params.permit!
    params[:book].each  do  |b|
      @book = Book.create(b)
    end
    redirect_to  :back
  end

  private 
    def  book_params
      params.require(:book).permit(:name,  :num,  :type_id,  :picture)
    end

    def  b_params
      params.require(:book).permit(:name,  :num,  :type_id,  :bn,  :user_id)
    end

    def  find_c_exit(id1,id2)
      Book.find_by_sql("select b.ubn from  borrow b  where b.book_id = #{id1} and b.user_id = #{id2}").size
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_f.html.erb
<div  id="n_i_t">
  <%=  form_for :info,  url:  infos_path do  |f|  %>
  <table  id="i_n_tab">
    <tr>
      <td colspan="2">添加书籍明细</td>
      <td></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">作者</td>
      <td  id="i_n_tdc"><%=  f.text_field  :author  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">出版社</td>
      <td  id="i_n_tdc"><%=  f.text_field  :p_place  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">出版年份</td>
      <td  id="i_n_tdc"><%=  f.text_field  :p_time  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">页数</td>
      <td  id="i_n_tdc"><%=  f.text_field  :p_num  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">语言</td>
      <td  id="i_n_tdc"><%=  f.text_field  :language  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">开本</td>
      <td  id="i_n_tdc"><%=  f.text_field  :format  %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr  id="i_n_tr">
      <td  id="i_n_tdl">简介</td>
      <td  id="i_n_tdc"><%=  f.text_field  :introduce %></td>
      <td  id="i_n_tdr"></td>
    </tr>
    <tr>
      <td colspan="2">
      <%=  f.hidden_field  :book_id ,  :value =>  @book.id  %>
      <%=  f.submit '保存'  %>
      <td>
      <td></td>
    </tr>
  </table>
  <%  end  %>
</div>

app/views/books/_form.html.erb
<script type="text/javascript">
  $(function  (){
    $("#book_name").blur(function (){
      var reg = /^[\u4e00-\u9fa5\w]{2,10}$/
      if (!$(this).val() == "") {
              if(reg.test($(this).val())==false){
              $("#error1").html("名称格式不正确");
              }else{
      $.ajax({
        type:  "get",
        url:  "/checkname/" +$(this).val(),
        data: "text",
        success:function (data){
          if  (data == "true"){
            $("#error1").html("名称可用");
            setTimeout('$("#error1").html("")',3000);
          }else{
            $("#error1").html("名称已存在");
            setTimeout('$("#error1").html("")',3000);
          }

        }
      });
    }
  }else{
    $("#error1").html("为空");
  }
    });
  });
</script>

<div  id="n_c_d">
    <%=  form_for(@book,  :html => {:multipart => true})  do  |f|  %>
      <table  id="n_tab">
         <tr>
        <td  id="tdl"> 类型</td>
        <td>
          <%= select(:book,:type_id,options_for_select(Type.find_con))%>
        </td>
        <td></td>
      </tr>
      <tr  id="tr">
        <td  id="tdl"><%=  f.label  :书名 %></td>
        <td><%=  f.text_field  :name,  :placeholder  =>  '1-50字符' %></td>
        <td  id="tdr">
          <span id="error"> 
             <%  if  !@book.errors[:name].blank?  %>
             <%=  @book.errors[:name][0] %>
             <%  end  %>
          </span>
          <span  id="error1" style="font-size: 10px;color: red"></span>
        </td>
      </tr>
      <tr id="tr">
        <td  id="tdl"><%=  f.label  :数量  %></td>
        <td><%=  f.text_field  :num ,:value  => 0%></td>
        <td>
          <span  id="error"> 
            <%  if  !@book.errors[:num].blank?  %>
              <%=  @book.errors[:num][0] %>
            <%  end  %>
          </span>
         </td>
      </tr>
      <tr  id="tr">
        <td  id="tdl"><%=  f.label  :Picture  %></td>
        <td><%= f.file_field :picture %></td>
      </tr>
      <tr id="tr">
        <td colspan="2"><%=  f.submit '保存' %> </td>
        <td></td>
      </tr>
  </table>
<%  end  %>
</div>

app/views/books/edit.html.erb
<style type="text/css">
#e_tab{
  width: 500px;
  font-size: 16px;
  font-weight: normal;
  height: 60px;
}
#i_n_tab{
  width: 500px;
  font-size: 18px;
  font-weight: normal;
}
#i_n_tdl{
  width: 100px;
  text-align:justify;
  -moz-text-align-last:justify;
  text-align-last:justify;
}
#i_n_tdr{
  width: 190px;
}
#i_n_tr{
  height: 20px;
}

#error{
 height: 30px;
 color: red;
 font-size: 10px;
 line-height: 10px;
}
</style>

<center  >
<%= form_for :book,  url: book_path(@book),   
                                          :html => {:multipart => true},
                                           method: :patch do |f| %>
  <table  id="e_tab">
    <tr>
      <td  colspan="2">更新书籍</td>
      <td  id="i_n_tdr"></td>
    </tr>
    <%=  f.hidden_field  :type_id ,  :value =>  @book.type_id %>
    <%=  f.hidden_field  :id ,  :value =>  @book.id  %>
    <tr>
      <td  id="i_n_tdl">书名</td>
       <td  id="i_n_tdc">
         <%= f.text_field :name,  :value  =>  @book.name,  
                                                        :readonly  =>  'readonly'  %></td>
      <td>
        <span id="error"> 
           <%  if  !@book.errors[:name].blank?  %>
           <%=  @book.errors[:name][0] %>
           <%  end  %>
        </span>
      </td>
    </tr>
    <tr>
      <td id="i_n_tdl">数量</td>
      <td  id="i_n_tdc">
        <%=  f.text_field  :num,  :value  =>  @book.num  %>
      </td>
      <td>
        <span  id="error"> 
          <%  if  !@book.errors[:num].blank?  %>
            <%=  @book.errors[:num][0] %>
          <%  end  %>
        </span>
      </td>
    </tr>
    <tr >
      <td  id="i_n_tdl"><%=  f.label  :Picture  %></td>
      <td  id="i_n_tdc"><%= f.file_field :picture %></td>
      <td>
        <span  id="error"> 
          <%  if  !@book.errors[:picture].blank?  %>
            <%=  @book.errors[:picture][0] %>
          <%  end  %>
        </span>
      </td>
    </tr>
    <tr>
      <td  colspan="2"><%=  f.submit  '保存'  %></td>
      <td></td>
    </tr>
  </table>
<%  end  %>
</center>

app/views/books/index.html.erb
<style type="text/css">
  table tr:hover {
      background-color: #0180FE;
      color: black;
      cursor:hand;
  }
</style>

<center>
<div  id="tab">
<table  >
<%  if  !@book.nil?   %>
  <caption>借出列表</caption>
    <tr class = "tr1">
      <th>图书类别</th>
      <th>图书名称</th>
      <th>可借数量</th>
      <th>借出数量</th>
      <th colspan="2">管理</th>
      <th>更新</th>
    </tr>
    <%  if  @book.size == 0  %>
    <tr>
      <td  colspan="6">记录为空</td>
    </tr>
    <%  else  %>
    <% @book.each do |book| %>
    <tr>
      <td><%=  Type.find_btype(book.type_id)%></td>
      <td><%=  book.name %></td>
      <td><%=  book.num %></td>
     <td>
       <%  if Book.find_ubn(book.id,current_user.id).nil? %>
         0
       <%  else  %>
         <%=  Book.find_ubn(book.id,current_user.id)  %>
       <%  end  %>
     </td>
     <td>
     <%=  form_for :book,   url: book_path(book.id) , 
                                                 remote:  true, 
                                                 method: :delete,   
                                                 data: { confirm: '确定删除？'} do  |f| %>
     <%=  f.hidden_field  :id,  :value  =>  book.id  %>
     <%=  f.submit  '删除'  %>
     <%  end  %>  
    <!--  <input id="bt_destroy_cib"  class="btn btn-mini btn-danger"  type="button"  value="删除" > -->                                                                                     
     </td>
     <td><%= link_to '查看', book_path(book) %></td>
     <td>
       <%=  link_to  '更新',edit_book_path(book)  %>
     </td>
     <%#= check_box_tag 'che', book.id %> 
   </tr>
  <%  end %>
  <%  end  %>
<%  else  %>
<caption>图书列表</caption>
  <tr class = "tr1">
    <th>图书类别</th>
    <th>图书名称</th>
    <th>可借数量</th>
    <th>借出数量</th>
    <th colspan="2">管理</th>
    <th>更新</th>
  </tr>
  <%  if  @books.size == 0  %>
  <tr>
    <td  colspan="6">记录为空</td>
  </tr>
  <%  else  %>
  <% @books.each do |book| %>
  <tr>
    <input type="hidden"  name="come_in_bill_id"  value="<%=  book.id %>">
    <td><%=  Type.find_btype(book.type_id)%></td>
    <td><%=  book.name %></td>
    <td><%=  book.num %></td>
   <td>
     <%  if Book.find_ubn(book.id,current_user.id).nil? %>
       0
     <%  else  %>
       <%=  Book.find_ubn(book.id,current_user.id)  %>
     <%  end  %>
   </td>
   <td>
   <%=  form_for :book,   url: book_path(book.id) , 
                                               remote:  true, 
                                               method: :delete,   
                                               data: { confirm: '确定删除？'},
                                               remote: true  do  |f| %>
   <%=  f.hidden_field  :id,  :value  =>  book.id  %>
   <%=  f.submit  '删除'  %>
   <%  end  %>  
  <!--  <input id="bt_destroy_cib"  class="btn btn-mini btn-danger"  type="button"  value="删除" > -->                                                                                     
   </td>
   <td><%= link_to '查看', book_path(book) %></td>
   <td>
     <%=  link_to  '更新',edit_book_path(book)  %>
   </td>
   <%#= check_box_tag 'che', book.id %> 
 </tr>
<%  end %>
<%  end  %>
<%  end  %>
</table>
</div>
<div   id="page">
<%  if  !@book.nil?  %>
  <%=  will_paginate  @book   %>
<%  else  %>
  <%=  will_paginate  @books   %>
<%  end  %>
</div>
</center>

app/views/books/new.html.erb
<style type="text/css">
  #n_back{
    width: 100px;
    height: 26px;
    line-height: 26px;
    text-align: center;
    font-size: 20px;
    border-radius: 5px; 
  }
  #n_c_d{
    height: 297px;
    width: 1280px;
  }

  #n_tab{
     width: 400px;
     height: 200px;
     text-align: center;
     border: 1px;
     font-size: 18px;
     font-weight: normal;
  }

  #tr{
    height: 50px;
  }
  #tdl{
    width: 80px;
    text-align: center;
  }
  #tdr{
    width: 150px;
    text-align: center;
  }
#error{
 height: 30px;
 color: red;
 font-size: 10px;
 line-height: 10px;
}
select{
  width: 210px;
}
</style>
<script type="text/javascript">
  $(function  (){
    $("#book__name").blur(function (){
      var reg = /^[\u4e00-\u9fa5\w]{2,40}$/
      if (!$(this).val() == "") {
              if(reg.test($(this).val())==false){
              $("#error").html("名称格式不正确");
              }else{
                  $.ajax({
                    type:  "get",
                    url:  "/books/checkname?name = " +$(this).val(),
                    data: "text",
                    success:function (data){
                      if  (data == "true"){
                        $("#error").html("名称可用");
                        setTimeout('$("#error").html("")',3000);
                      }else{
                        $("#error").html("名称已存在");
                        setTimeout('$("#error").html("")',3000);
                      }

                    }
                  });
    }
  }else{
    $("#error").html("为空");
  }
    });
  });

  function  getOK(){

  }
</script>

<center>
<%#= render 'form' %>

<%=  form_tag(batch_add_books_path, method:  "get")   do %>
  <table  id="parttable">
     <caption>Add</caption>
     <tr>
        <th>类型</th>
        <th>书名</th>
        <th>数量</th>
        <th>操作</th>
        <th>MESSAGE</th>
      </tr>
      <tr>
        <td><%= select_tag("book[][type_id]" ,options_for_select(Type.find_con))%></td>
        <td><%=  text_field_tag  "book[][name]"  %></td>
        <td><%=  number_field_tag "book[][num]"  %></td>
        <td>
          <input type="button"   value="增加" id="addTable" onclick="add_tr(this)"/>
          <input type="button"   value="删除" id="deleteTable" onclick="del_tr(this)"/>
        </td>
        <td><span  id="error"></span></td>
      </tr>
  </table>
<%=  submit_tag '保存' %>
<%  end  %>
<%#= select(:book,:type_id,options_for_select(Type.find_con))%>  
</center>
<script type="text/javascript">
  function add_tr(obj) {
     var tr = $(obj).parent().parent();
     tr.after(tr.clone());
   }
   function del_tr(obj) {
       $(obj).parent().parent().remove();
     }
</script>

app/views/books/show.html.erb
<style type="text/css">
#stab{
  width: 500px;
  font-weight: normal;
}
#stab tr{
  height: 18px;
}
  #stdl{
   width: 100px;
   font-size: 16px;
   text-align:justify;
   -moz-text-align-last:justify;
   text-align-last:justify;
  }
 #stdr{
  width: 300px;
  font-size: 14px;
  font-weight: normal;
 } 
  #ed{
    width: 80px;
  }
  #b_b{
    width: 300px;
    height: 15px;
  }
</style>
<center>
<div  id="st_d">
<table id="stab">
  <caption>图书信息</caption>
  <tr>
    <td  id="stdl">图书类别</td>
    <td  id="stdr"><%=  Type.find_btype(@books.type_id)%></td>
    <td rowspan="6">
      <%= image_tag(@books.picture_url, :width => 100) if @books.picture.present? %>
    </td>
  </tr>
  <tr  id="stdr">
    <td  id="stdl">图书名称</td>
    <td><%=  @books.name  %></td>
  </tr>
  <tr>
    <td  id="stdl">可借数量</td>
    <td  id="stdr"><%=  @books.num  %></td>
  </tr>
  <tr>
    <td  id="stdl">借出总量</td>
    <td  id="stdr"><%=  @books.bn  %></td>
  </tr>
  <tr>
    <td  id="stdl">创建时间</td>
    <td  id="stdr"><%=  @books.created_at  %></td>
  </tr>
  <tr>
    <td id="stdl" style="height: 20px;">借出/还入</td>
    <td>
      <table id = "b_b">
        <tr>
         <td style="width: 150px;">
         <%  if Book.find_ubn(@books.id,current_user.id)  == 0   || Book.find_ubn_e(@books.id,current_user.id)  ==  0  %>
           <span  style="font-size: 12px;">无借出</span>
         <%  else  %>
           <%=  form_for :book,  remote:  true,
                                                      url: book_path(@books.id) ,   
                                                      method: :patch  do  |f| %>
          <input type="hidden" name="num" value=2>
          <%=  f.number_field  :bn,  
                                                   :style  =>  "width:50px;font-size:12px;font-weight:normal",
                                                   :min =>0,  :max  => Book.find_ubn(@books.id,current_user.id) ,
                                                   :value  =>  Book.find_ubn(@books.id,current_user.id)  %>
          <%=  f.hidden_field  :type_id,  :value  =>  @books.type_id  %>
          <%=  f.hidden_field  :user_id,  :value  =>  current_user.id  %>
          <%=  f.submit  '还入', :style  =>  "width:50px;height:26px;font-size:16px;"   %>
          <%  end  %>
          <%  end  %>
         </td>
         <td>
           <%  if  @books.num >0  %>
           <%=  form_for :book,   remote:  true,
                                                       url: book_path(@books.id) ,
                                                       method: :patch    do  |f| %>
            <input type="hidden" name="num" value=3>
           <%=  f.number_field  :bn, 
                                                    :style  =>  "width:50px;font-size:12px;font-weight:normal",
                                                    :min  =>  0,   :max  =>  @books.num,
                                                    :value  => 0  %>
           <%=  f.hidden_field  :type_id,  :value  =>  @books.type_id  %>
           <%=  f.hidden_field  :user_id,  :value  =>  current_user.id  %>
           <%=  f.submit  '借出' , :style  =>  "width:50px;height:26px;font-size:16px;"  %>
           <%  end  %>
           <%  else %>
            不可借
           <% end %>
         </td>
        </tr>
      </table>
    </td>
  </tr>
  </table>
  <%  if  @info.size  ==  0  %>
  <div>
  <%= link_to '添加明细', new_info_path %>
  </div>
  <%  else  %>
  <%  @info.each  do  |infos|  %>
  <table  id="stab">
  <tr>
    <td id="ed"><%=  link_to  '更新明细',edit_info_path(infos.id)  %></td>
    <td>出版信息</td>
  </tr>
  <tr>
    <td  id="stdl">作者</td>
    <td  id="stdr"><%=  infos.author %></td>
  </tr>
  <tr>
    <td  id="stdl">出版社</td>
    <td  id="stdr"><%=  infos.p_place %></td>
  </tr>
  <tr>
    <td  id="stdl">出版年份</td>
    <td  id="stdr"><%=  infos.p_time  %></td>
  </tr>
  <tr>
    <td  id="stdl">页码</td>
    <td  id="stdr"><%=  infos.p_num  %></td>
  </tr>
  <tr>
    <td  id="stdl">语种</td>
    <td  id="stdr"><%=  infos.language  %></td>
  </tr>
  <tr>
    <td  id="stdl">开本</td>
    <td  id="stdr"><%=  infos.format %></td>
  </tr>
  <tr >
    <td  id="stdl">简介</td>
    <td  id="stdr" style="height: 55px;font-size: 13px;"><%=  infos.introduce %></td>
  </tr>
</table>
<%  end  %>
<%  end  %>
</div>
</center>